title: VPR Arxiv Daily
description: Automatically Update Visual Place Recognition Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/runjtu/vpr-arxiv-daily
  another_url: https://github.com/runjtu/vpr-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: runjtu

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
